services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-vulnsentinel}
    volumes:
      - ./volumes/postgres/data:/var/lib/postgresql/data
