kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: vulnsentinel
nodes:
  - role: control-plane
    image: kindest/node:v1.33.1
    extraMounts:
      - hostPath: C:\Users\nisar\OneDrive\Desktop\Projects\VulnSentinel AI\volumes
        containerPath: /vulnsentinel-volumes
  - role: worker
    image: kindest/node:v1.33.1
    extraMounts:
      - hostPath: C:\Users\nisar\OneDrive\Desktop\Projects\VulnSentinel AI\volumes
        containerPath: /vulnsentinel-volumes
  - role: worker
    image: kindest/node:v1.33.1
    extraMounts:
      - hostPath: C:\Users\nisar\OneDrive\Desktop\Projects\VulnSentinel AI\volumes
        containerPath: /vulnsentinel-volumes
