apiVersion: batch/v1
kind: Job
metadata:
  name: db-migrate
  namespace: vulnsentinel
spec:
  ttlSecondsAfterFinished: 3600
  backoffLimit: 1
  template:
    metadata:
      labels:
        app: db-migrate
    spec:
      restartPolicy: Never
      containers:
        - name: db-migrate
          image: vuln-worker:local
          imagePullPolicy: IfNotPresent
          command:
            - sh
            - -c
            - alembic upgrade head
          env:
            - name: POSTGRES_HOST
              value: postgres
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_DB
              value: vulnsentinel
